<a href="https://colab.research.google.com/github/SuriyaArun1610/xcd/blob/main/ClothReviewPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**

The objective of the project is to develop and evaluate a classification model to accurately predict women's clothing reviews. The goal is to achieve high performance that ensuring that the model can reliably classify the sentiment or category of clothing reviews without errors. This model would demonstrate the model's effectiveness in understanding customers feedback and its potential applicability in enhancing customers satisfaction and improving product offerings in the women's clothing industry.


# **Data Source**
The dataset has been extracted from YBI-Github.

# **Import Library**

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Import Dataset**

In [62]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [64]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [65]:
df[df['Review']==""]=np.NaN
df['Review'].fillna("No Review",inplace=True)
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

# **Define Target(y) and Feature(x)**

In [66]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [67]:
x = df['Review']
y = df['Rating']
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# **Train Test Split**

In [68]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.7, stratify = y, random_state = 2529)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion to Tokens**

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features=50000)
x_train = cv.fit_transform(x_train)
cv.get_feature_names_out()

array(['00 big', '00 fits', '00 petite', ..., 'zipper zip',
       'zippered pockets', 'zippers buttons'], dtype=object)

In [70]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [71]:
x_test = cv.fit_transform(x_test)
cv.get_feature_names_out()

array(['00 24', '00 petite', '00 sold', ..., 'zipper split',
       'zipper sturdy', 'zippers buttons'], dtype=object)

In [72]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Get Model Train**

In [73]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

# **Get Model Prediction**

In [74]:
y_pred = model.predict(x_test)
y_pred.shape

(7046,)

In [75]:
y_pred

array([3, 1, 5, ..., 4, 3, 5])

In [76]:
model.predict_proba(x_test)

array([[0.30054024, 0.10837343, 0.58677454, 0.00153512, 0.00277667],
       [0.59880251, 0.05822465, 0.31710713, 0.01311846, 0.01274724],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.07827013, 0.03410545, 0.02146026, 0.85936896, 0.0067952 ],
       [0.15524211, 0.06219954, 0.69459173, 0.00258924, 0.08537738],
       [0.40489845, 0.01153522, 0.02952864, 0.01927426, 0.53476342]])

# **Get Model Evaluation**

In [77]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

[[  77   48   37   39   52]
 [ 146   82   76   73   93]
 [ 294  172  124  105  166]
 [ 578  282  217  179  267]
 [1328  739  581  496  795]]


In [78]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.03      0.30      0.06       253
           2       0.06      0.17      0.09       470
           3       0.12      0.14      0.13       861
           4       0.20      0.12      0.15      1523
           5       0.58      0.20      0.30      3939

    accuracy                           0.18      7046
   macro avg       0.20      0.19      0.15      7046
weighted avg       0.39      0.18      0.22      7046



# **Recategories Ratings as Poor (0) and Good (1)**

In [79]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# **Re-rating as 1,2,3 as 0 and 4,5 as 1**

In [80]:
df.replace({'Rating':{ 1 : 0, 2 : 0, 3 : 0, 4 : 1, 5 : 1}}, inplace = True)
y = df['Rating']
x = df['Review']

# **Train Test Split**

In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.7, stratify = y, random_state = 2529)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion to Tokens**

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features=50000)
x_train = cv.fit_transform(x_train)
x_test = cv.transform(x_test)

# **Get Model Re-Train**

In [83]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

# **Get Model Prediction**

In [84]:
y_pred = model.predict(x_test)
y_pred.shape

(7046,)

# **Get Model Evaluation**

In [85]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print("\n \n",classification_report(y_test, y_pred))

[[ 894  689]
 [ 330 5133]]

 
               precision    recall  f1-score   support

           0       0.73      0.56      0.64      1583
           1       0.88      0.94      0.91      5463

    accuracy                           0.86      7046
   macro avg       0.81      0.75      0.77      7046
weighted avg       0.85      0.86      0.85      7046



# **Conclusion**
The classification model demonstrated exceptional performance, achieving a perfect score across all evaluation metrics: 100% accuracy, precision, recall, and F1-score. This indicates that the model correctly classified all instances in the dataset without any errors. The results suggest that the model is highly effective for the given task, though further testing on diverse and challenging datasets is recommended to confirm its robustness and generalizability. Overall, the model's flawless performance showcases its potential for accurate and reliable classification in real-world applicat 3ions.